version: '2'
services:
  jenkins:
    image: "jenkins/jenkins:lts-jdk8"
    ports:
     - "8080:8080"
    volumes:
      - "jenkins_home:/var/jenkins_home"
    networks:
      - demo
  sonarqube:
    image: "sonarqube:6.4"
    ports:
     - "9000:9000"
    networks:
      - demo
  tomcat:
    image: 'tutum/tomcat:6.0'
    ports:
      - 10000:8080
    environment:
      - TOMCAT_PASS=admin
    networks:
      - demo
networks:
  demo:
volumes:
  jenkins_home:
    driver: local
